# Generated by Django 4.1 on 2022-08-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
